version: '2'
services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  fluentd:
    build: fluentd/
    volumes:
      - ./fluentd/:/etc/fluent/
    ports:
      - "24224:24224"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

  application:
    image: nginx
    ports:
      - "80:80"
    logging:  
      driver: "fluentd"
      options:
        fluentd-address: 172.18.0.4:24224 # Replace the fluentd server IP address 
    networks:
      - docker_elk 
    depends_on:
      - elasticsearch 
networks:
  docker_elk:
    driver: bridge
